/* Generated by JTB 1.5.1 */
package grammars.y.syntaxtree;

@SuppressWarnings("javadoc")
public interface INodeList extends INode {

  public void addNode(final INode n);

  public INode elementAt(int i);

  public java.util.Iterator<INode> elements();

  public int size();

}
