/* Generated by JTB ${jtb_version} from ${template_file_name} */
<#--
<#assign nowDT = .now>
<#assign nowDate = nowDT?date>
<#assign nowTime = nowDT?time>
/* Generated by JTB ${jtb_version} from ${template_file_name} on ${nowDate?iso_local} ${nowTime?iso_local} */
-->