/* Generated By:JavaCC: Do not edit this line. NoOptionsSectionGrammarConstants.java */
package grammars.z;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NoOptionsSectionGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int WS = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<ID>",
    "<WS>",
  };

}
