/* Generated by JTB 1.4.5 */
package EDU.purdue.jtb.syntaxtree;

import EDU.purdue.jtb.visitor.*;

/**
 * JTB node class for the production RegularExprProduction:<br>
 * Corresponding grammar :<br>
 * f0 -> [ %0 #0 "<" #1 "*" #2 ">"<br>
 * .. .. | %1 #0 "<" #1 < IDENTIFIER ><br>
 * .. .. . .. #2 ( $0 "," $1 < IDENTIFIER > )* #3 ">" ]<br>
 * f1 -> RegExprKind()<br>
 * f2 -> [ #0 "[" #1 "IGNORE_CASE" #2 "]" ]<br>
 * f3 -> ":"<br>
 * f4 -> "{"<br>
 * f5 -> RegExprSpec()<br>
 * f6 -> ( #0 "|" #1 RegExprSpec() )*<br>
 * f7 -> "}"<br>
 */
public class RegularExprProduction implements INode {

  /** A child node */
  public NodeOptional f0;

  /** A child node */
  public RegExprKind f1;

  /** A child node */
  public NodeOptional f2;

  /** A child node */
  public NodeToken f3;

  /** A child node */
  public NodeToken f4;

  /** A child node */
  public RegExprSpec f5;

  /** A child node */
  public NodeListOptional f6;

  /** A child node */
  public NodeToken f7;

  /** The serial version uid */
  private static final long serialVersionUID = 145L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   * @param n3 next child node
   * @param n4 next child node
   * @param n5 next child node
   * @param n6 next child node
   * @param n7 next child node
   */
  public RegularExprProduction(final NodeOptional n0, final RegExprKind n1, final NodeOptional n2, final NodeToken n3, final NodeToken n4, final RegExprSpec n5, final NodeListOptional n6, final NodeToken n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  /**
   * Constructs the node with only its non NodeToken child node(s).
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   * @param n3 next child node
   * @param n4 next child node
   */
  public RegularExprProduction(final NodeOptional n0, final RegExprKind n1, final NodeOptional n2, final RegExprSpec n3, final NodeListOptional n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = new NodeToken(":");
    f4 = new NodeToken("{");
    f5 = n3;
    f6 = n4;
    f7 = new NodeToken("}");
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
