/* Generated by JTB 1.4.5 */
package EDU.purdue.jtb.syntaxtree;

import EDU.purdue.jtb.visitor.*;

/**
 * JTB node class for the production ComplexRegularExpressionUnit:<br>
 * Corresponding grammar :<br>
 * f0 -> . %0 StringLiteral()<br>
 * .. .. | %1 #0 "<" #1 Identifier() #2 ">"<br>
 * .. .. | %2 CharacterList()<br>
 * .. .. | %3 #0 "(" #1 ComplexRegularExpressionChoices() #2 ")"<br>
 * .. .. . .. #3 ( &0 "+"<br>
 * .. .. . .. .. | &1 "*"<br>
 * .. .. . .. .. | &2 "?"<br>
 * .. .. . .. .. | &3 $0 "{" $1 IntegerLiteral()<br>
 * .. .. . .. .. . .. $2 [ £0 ","<br>
 * .. .. . .. .. . .. .. . £1 [ IntegerLiteral() ] ] $3 "}" )?<br>
 */
public class ComplexRegularExpressionUnit implements INode {

  /** A child node */
  public NodeChoice f0;

  /** The serial version uid */
  private static final long serialVersionUID = 145L;

  /**
   * Constructs the node with its child node.
   *
   * @param n0 the child node
   */
  public ComplexRegularExpressionUnit(final NodeChoice n0) {
    f0 = n0;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
